server:
  port: 8761
  maxThreadsForPeerReplication: 0

spring:
  application:
    name: eurekaServer
    
  
eureka:

  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761
  
